export const SET_COUNTRIES = 'SET_COUNTRIES';
export const SET_USER = 'SET_USER';
export const SET_CURRENT_TEAM = 'SET_CURRENT_TEAM';
export const SET_TEAMS = 'SET_TEAMS';
export const SET_GAME_NAME = 'SET_GAME_NAME';

// navigation actions
export const IS_TEAMS_SELECTED_ON_GAME_CREATE = 'IS_TEAMS_SELECTED_ON_GAME_CREATE';
export const IS_GAME_SELECTED_ON_LOBBY = 'IS_GAME_SELECTED_ON_LOBBY';
export const IS_DELETE_ENABLED_ON_LOBBY = 'IS_DELETE_ENABLED_ON_LOBBY';
export const IS_GAME_WAITING_FOR_PLAYERS = 'IS_GAME_WAITING_FOR_PLAYERS';
export const IS_GAME_READY_TO_START = 'IS_GAME_READY_TO_START';
export const IS_PAGE_LOADING = 'IS_PAGE_LOADING';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_GAME = 'SET_GAME';
export const SET_PLAYER_AVATAR = 'SET_PLAYER_AVATAR';

// game proper
export const SET_PLAYER_TO_TACKLE = 'SET_PLAYER_TO_TACKLE';
export const SET_PLAYER_TO_RECEIVE_BALL = 'SET_PLAYER_TO_RECEIVE_BALL';
export const SET_BALL_HANDLER = 'SET_BALL_HANDLER';
export const LOCK_TURN = 'LOCK_TURN';
export const UNLOCK_TURN = 'UNLOCK_TURN';
export const SET_GAME_STATUS = 'SET_GAME_STATUS';
