export const SET_COUNTRIES = 'SET_COUNTRIES';
export const SET_USER = 'SET_USER';

// navigation actions
export const IS_TEAMS_SELECTED_ON_GAME_CREATE = 'IS_TEAMS_SELECTED_ON_GAME_CREATE';
export const IS_GAME_SELECTED_ON_LOBBY = 'IS_GAME_SELECTED_ON_LOBBY';
export const IS_DELETE_ENABLED_ON_LOBBY = 'IS_DELETE_ENABLED_ON_LOBBY';
export const IS_GAME_WAITING_FOR_PLAYERS = 'IS_GAME_WAITING_FOR_PLAYERS';
export const IS_GAME_READY_TO_START = 'IS_GAME_READY_TO_START';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_GAME_ID = 'SET_GAME_ID';
export const SET_PLAYER_AVATAR = 'SET_PLAYER_AVATAR';
