version: "2"
services:
  app:
    image: 097133312331.dkr.ecr.us-east-1.amazonaws.com/rugbyunion:latest
    ports:
      - "58426:8080"
    environment:
      - REACT_APP_RUNTIME_PORT=58426
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "30149:27017"