version: '3'

services:
  whg.engagementapp.api:
    image: jsnmgpnty/whg-app
    ports:
      - "58747:80"
    networks:
      - whg-network
    depends_on:
      - mongo
      - redis
  mongo: 
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - whg-network
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - whg-network
  app:
    build: .
    ports:
      - "58426:8080"
    environment:
      - REACT_APP_RUNTIME_ENV=${REACT_APP_RUNTIME_ENV}
      - NODE_ENV=${NODE_ENV}
    networks:
      - whg-network
networks:
  whg-network:
    driver: bridge
volumes:
  mongo-data: