version: "2"
services:
  app:
    restart: always
    build: .
    ports:
      - "58426:8080"
    environment:
      - REACT_APP_RUNTIME_PORT=58426
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "30149:27017"
volumes:
  mongodata: